parking/parking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from administrator import views as a
from car import views as car
from device import views as device
from parkinglot import views as park
from company import views as com
from wechat import views as wechat
from chargerule import views as charge
from realtime import views as realtime
from account import views as ac
from business import views as b
from manager import views as m


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('meta.urls')),


    # administrator
    path('',a.base),
    path('administrator/login/',a.login),
    path('administrator/logout/',a.logout),
    path('base/', a.base),   
    path('index/', a.index),
    path('administrator/log/', a.log),
    path('administrator/role/', a.role),
    path('administrator/role/<int:id>/', a.get_role),
    path('administrator/user/',a.user),
    path('administrator/modify/',a.modify),
    

    # user



    # car 
    path('car/inner_car/', car.inner_car),  
    

    # parkinglot

    path('parkinglot/parking_lot/',park.parking_lot),
    path('parkinglot/gate/',park.gate),
    path('parkinglot/worker/', park.worker),
    path('parkinglot/zone/',park.zone),
    path('parkinglot/place/',park.place),
    path('parkinglot/calendar/',park.calendar),



    # company

    path('company/company/',com.company),



    # device

    path('device/brake/',device.brake),
    path('device/camera/',device.camera),
    path('device/groundsensor/',device.groundsensor),



    # chargerule

    path('chargerule/baserule/',charge.base_rule),
    path('chargerule/card/',charge.card),
    path('chargerule/coupon/',charge.coupon),
    path('chargerule/cardtype/',charge.card_type),
    path('chargerule/coupontype/',charge.coupon_type),
    path('chargerule/chargedemo/',charge.chargedemo),
    path('chargerule/check_coupon/',charge.check_coupon),


    # realtime

    path('realtime/parkin/',realtime.parkin),
    path('realtime/in_out/',realtime.in_out),
    path('realtime/bill/',realtime.bill),


    # wechat
    path('wechat/parkin/<int:parkinglot_id>/<int:gate_id>/',wechat.parkin),
    path('wechat/parkout/<int:parkinglot_id>/<int:gate_id>/',wechat.parkout),
    path('wechat/parkout/<int:parkinglot_id>/',wechat.parkout),
    path('wechat/personal/mybill/<int:id>/',wechat.mybill),
    path('wechat/personal/mybill/',wechat.mybill),
    path('wechat/personal/mycard/',wechat.mycard),
    path('wechat/personal/mycoupon/',wechat.mycoupon),
    path('wechat/personal/myplate/bound/',wechat.bound),
    path('wechat/personal/myplate/',wechat.myplate),
    path('wechat/personal/',wechat.personal),
    path('wechat/problem/',wechat.problem),
    path('wechat/scan/coupon/<int:id>/<str:code>/',wechat.scan_coupon),


    #account
    path('account/spec_pass/',ac.spec_pass),
    path('account/correct/',ac.correct),
    path('account/record/',ac.record),
    path('account/personal/',ac.personal,name='personal'),
    path('account/begin_work/',ac.begin_work),


    #business
    path('business/com_login/',b.com_login),
    path('business/apply/<int:tc_id>/',b.apply),
    path('business/grant/',b.grant),
    path('business/ticket/<int:tc_id>/',b.ticket),

    #manager
    path('manager/manage_login/',m.manage_login),
    path('manager/staff_list/<str:parkinglot>/',m.staff_list),
    path('manager/manage_home/',m.manage_home),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parking/chargerule/models.py
from django.db import models


from administrator.models import AdminUser as User
from parkinglot.models import ParkingLot 
from company.models import Company
from meta.models import User as CarUser


import datetime


'''计费规则模块'''


class Coupons(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '优惠券'

    type = models.IntegerField(choices=[(0, '打折券'),(1, '代金券'),(2, '抵扣券'),(3, '满时券')])

    name = models.CharField(max_length=200, verbose_name='名称')
    detail = models.CharField(max_length=200, verbose_name='说明')

    rate = models.FloatField(null=True, blank=True, verbose_name='折扣率')
    money = models.FloatField(null=True, blank=True, verbose_name='金额')
    hours = models.FloatField(null=True, blank=True, verbose_name='小时数')

    money1 = models.FloatField(null=True, blank=True, verbose_name='金额')
    hours1 = models.FloatField(null=True, blank=True, verbose_name='小时数')
    money2 = models.FloatField(null=True, blank=True, verbose_name='金额')
    hours2 = models.FloatField(null=True, blank=True, verbose_name='小时数')
    money3 = models.FloatField(null=True, blank=True, verbose_name='金额')
    hours3 = models.FloatField(null=True, blank=True, verbose_name='小时数')
    money4 = models.FloatField(null=True, blank=True, verbose_name='金额')
    hours4 = models.FloatField(null=True, blank=True, verbose_name='小时数')

    is_delete = models.IntegerField(choices=[(0, '未删除'),(1, '已删除')], default=0)
    create_time = models.DateTimeField(auto_now_add=True, null=True)
    update_time = models.DateTimeField(auto_now=True, null=True)

    def rule(self):
        if self.type == 0:
            return '计费打 %s 折'% (self.rate/10)
        elif self.type == 1:
            return '计费减免 %s 元' % (self.money)
        elif self.type == 2:
            return '%s 个小时内均计费为 %s 元, 超出部分正常计费' %(self.hours, self.money)
        else:
            s = ''
            if self.money1 and self.hours1:
                s = s + '前 %s 小时计费为 %s 元;'%(self.hours1, self.money1)
            if self.money2 and self.hours2:
                s = s + '\n前 %s 小时计费为 %s 元;'%(self.hours2, self.money2)
            if self.money3 and self.hours3:
                s = s + '\n前 %s 小时计费为 %s 元;'%(self.hours3, self.money3)
            if self.money4 and self.hours4:
                s = s + '\n前 %s 小时计费为 %s 元;'%(self.hours4, self.money4)
            return s


class TicketRecord(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '优惠券出售记录'

    parkinglot = models.ForeignKey(ParkingLot, on_delete=models.SET_NULL, null=True)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True)

    ticket_type = models.IntegerField(choices=[(0, '折扣券'),(1, '代金券'),(2, '抵扣券'),(3, '满时券')])

    coupons = models.ForeignKey(Coupons, on_delete=models.SET_NULL, null=True)

    buy_time = models.DateTimeField(verbose_name='购买时间',auto_now_add=True,null=True)
    amount = models.IntegerField(null=True, verbose_name='购买上限')
    price = models.FloatField(default=0,verbose_name='单价',null=True)
    extra = models.IntegerField(default=0,verbose_name='余量')

    start_date = models.DateTimeField(null=True, verbose_name='起始日期')
    end_date = models.DateTimeField(null=True, verbose_name='截止日期')

    start_time1 = models.FloatField(null=True, verbose_name='优惠时段起点')
    end_time1 = models.FloatField(null=True, verbose_name='优惠时段截止')

    start_time2 = models.FloatField(null=True, verbose_name='优惠时段起点')
    end_time2 = models.FloatField(null=True, verbose_name='优惠时段截止')
    coucode = models.ImageField(null=True,verbose_name='券码',upload_to='coucode/')
    qrrandom = models.CharField(max_length=30,verbose_name='随机数',null=True)
    superpose = models.IntegerField(default=0,verbose_name='是否可叠加',choices=[(0,'否'),(1,'是')])
    status = models.IntegerField(default=0,choices=[(0,'待审核'),(1,'已通过'),(2,'审核失败')])

    # is_delete = models.IntegerField(choices=[(0, '未删除'),(1, '已删除')], default=0)


class CardType(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '月卡类型'

    status = models.IntegerField(default=0)
    name = models.CharField(max_length=30, verbose_name='名称')
    work = models.TextField(max_length=30,null=True,verbose_name='工作开始') 
    relax = models.TextField(max_length=30,null=True,verbose_name='休息开始')
    diff_type = models.IntegerField(null=True,verbose_name='减免指标',choices=[(0,'工作日'),(1,'自定义')],default=0)
    free = models.TextField(max_length=30,null=True,verbose_name='周一优惠开始') 
    free_tu = models.TextField(max_length=30,null=True,verbose_name='周二优惠开始') 
    free_we = models.TextField(max_length=30,null=True,verbose_name='周三优惠开始') 
    free_th = models.TextField(max_length=30,null=True,verbose_name='周四优惠开始') 
    free_fr = models.TextField(max_length=30,null=True,verbose_name='周五优惠开始') 
    free_sa = models.TextField(max_length=30,null=True,verbose_name='周六优惠开始') 
    free_su = models.TextField(max_length=30,null=True,verbose_name='周日优惠开始') 


class Card(models.Model):
    class Meta:
        verbose_name = verbose_name = '月卡'

    status = models.IntegerField(default=0)
    owner = models.CharField(max_length=30,null=True,verbose_name='持卡人')
    car_number = models.CharField(max_length=30,null=True,verbose_name='车牌号')
    phone = models.CharField(max_length=30,verbose_name='联系人电话')
    my_card = models.ForeignKey('CardType',null=True,blank=True, on_delete=models.CASCADE,verbose_name='卡片类型')
    valid_start = models.DateTimeField(null=True , blank=True, verbose_name='有效开始')
    valid_end = models.DateTimeField(null=True , blank=True, verbose_name='有效结束')
    suit = models.ManyToManyField(ParkingLot,verbose_name='所属停车场',related_name='parkinglot_card')

    def get_time(datetime,end):
        if datetime <10:
            datetime = '0'+str(datetime)

        st = str(end.year)+'-'+str(end.month)+'-'+str(end.day) +' '+datetime+':00:00'
        return datetime.datetime.strptime(st,'%Y-%m-%d %H:%M:%S')



    def set_valid_date(self):
        

        self.valid_start =now
        now = datetime.datetime.now()
        end = now
        diff = end.month - now.month
        if now.day == 1:
            
            while  diff == 0:
                end += datetime.timedelta(days=1)
        else:
            while  diff < 2:
                end += datetime.timedelta(days=1)

        self.valid_end = get_time(0,end)
        self.save()

    # 普通月卡计费
    def normal_card_cal(self,start,end):

        # 参数：start,end 
        # type:datetime

        # 计算单日需计费小时数
        def nor_one_cal(obj,start,end):
            o_start = obj.valid_start
            o_end = obj.valid_end
            diff2 = start.hour - o_start.hour
            diff3 = end.hour - o_end.hour
            diff4 = end.hour - o_start.hour
            diff5 = start.hour - o_end.hour
            e_mi = end.minute/60
            s_mi = start.minute/60  
            if diff2 < 0 :
                if diff3 >=0:
                    result = - diff2 - diff3 +e_mi - s_mi   
                else:
                    if diff4 < 0:
                        result = end + e_mi - start - s_mi
                    else:
                        result = o_start - start - s_mi
            else:
                if diff5 <0:
                    result = end + e_mi -o_end.hour
                else:
                    result = end + e_mi - start - s_mi
            return result


        diff = end.day-start.day
        diff1 = self.valid_end - self.valid_start 
        price1 = 24-diff1

        if diff > 0:
            results = nor_one_cal(self,start,get_time(23,start)) +(diff-1)*price1 + nor_one_cal(self,get_time(0,end),end)
        else:
            results = nor_one_cal(self,start,end)
        return results


#基础规则
class BaseRule(models.Model):
    class Meta:
        verbose_name =verbose_name_plural ='基础规则'

    status = models.IntegerField(default=0)
    parkinglot = models.ForeignKey(ParkingLot,on_delete=models.SET_NULL, null=True)
    per_hour = models.FloatField(default=0,verbose_name='小时费')
    free_time = models.IntegerField(default=0,verbose_name='免费时间')#单位：分钟
    day_max = models.FloatField(default=0,verbose_name='单日最大费用时段')
    min_price = models.IntegerField(default=0,verbose_name='最短计价时间')#单位：分钟
            

class UserCoupon(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '用户和券'

    user = models.ForeignKey(CarUser, on_delete=models.SET_NULL, null=True, blank=True)
    car_number = models.CharField(max_length=200, null=True, blank=True, verbose_name='车牌')
    ticket_record = models.ForeignKey(TicketRecord, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupons, null=True, on_delete=models.CASCADE)
    status = models.IntegerField(default=0, choices=[(0, '未使用'),(1, '已使用')])

    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    use_time = models.DateTimeField(auto_now_add=True, verbose_name='使用时间')













        

parking/chargerule/templates/check_coupon.html
{% extends 'iframe.html' %}
{% block content %}
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <ol class="col-lg-5 breadcrumb">
                            <li>计费规则</li>
                            <li>优惠券审核</li>
                        </ol>
                        <div class="ibox-tools">
                            <a onclick="window.location.href=window.location.href; "><i class="fa fa-refresh animated rotateIn"></i>&nbsp; 重新载入</a>
                        </div>
                    </div>
                    <div class="ibox-content" id="searchForm">
                        <div class="form-inline ">
                            <div class="form-inline">
                                <form id='query_form' action='' method="post">
                                    {% csrf_token %}
                                    <div class="form-group" style="width: 200px">
                                        <select data-placeholder="选择停车场" class="form-control chosen-select" child-id='gate_a'  name="parkinglot_id" style="display: none;">
                                            <option value=''>选择停车场</option>
                                            {% for i in parkinglots %}
                                                <option value='{{i.id}}' 
                                                {% if p == i.id %}selected{% endif %}
                                                >{{i.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div> &nbsp;&nbsp;
                                    <div class="form-group" style="width: 200px">
                                        <select data-placeholder="选择商家" class="form-control chosen-select" name="company_id" id='gate_a' style="display: none;">
                                            <option value="" selected="selected">选择商家</option>
                                            {% for i in companies %}
                                            <option value='{{i.id}}' 
                                                {% if c == i.id %}selected{% endif %}
                                                >{{i.name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>&nbsp;&nbsp;
                                    <div class="form-group" style="width: 200px">
                                        <select data-placeholder="选择审核状态" class="form-control chosen-select" name="status" id='gate_a' style="display: none;">
                                            <option value="" selected="selected">选择审核状态</option>
                                            <option value="0"{% if s == 0 %}selected{% endif %}>审核中</option>
                                            <option value="1" {% if s == 1 %}selected{% endif %}>审核通过</option>
                                            <option value="2"{% if s == 2 %}selected{% endif %}>审核失败</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <input type='hidden' name='action' value='search' />
                                        <input type='hidden' name='page' value='{{page}}' id='page' />
                                        <input type='hidden' name='pagesize' value='{{pagesize}}' id='pagesize' />
                                        <button id='search-btn' class="btn btn-primary search-btn " type="button" style="display: inline-block;">
                                            <i class="fa fa-search"></i> 查 询
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-6 m-b-xs">
                                <button onclick="su('pass')" type="button" id="Add" class=" btn btn-primary model-btn" style="display: inline-block;"><i class="fa fa-plus"></i>&nbsp;通过</button>
                                <button onclick="su('refuse')" type="button" id="delete-btn" class="btn btn-primary " style="display: inline-block;"><i class="fa fa-trash"></i>&nbsp;拒绝</button>
                            </div>
                            <div class="col-sm-3 m-b-xs"></div>
                        </div>
                        <div class="table-responsive">
                            <form id='op-form' action="" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="action" value="11">
                                <table class="table table-striped  table-hover">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>序号</th>
                                            <th>停车场</th>
                                            <th>商家</th>
                                           <!--  <th>优惠券类型</th> -->
                                            <th>优惠券名称</th>
                                            <th>限额</th>
                                            <th>余量</th>
                                            <th>有效截至</th>
                                            <th>状态</th>
                                           <!--  <th>操作</th> -->
                                        </tr>
                                    </thead>
                                    <tbody id="data-view">
                                        {% for i in objects %}
                                            <tr>
                                                <td><input name='ids' type='checkbox' value='{{i.id}}' /></td>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{{ i.parkinglot.name }}</td>
                                                <td>{{ i.company.name }}</td>
                                               <!--  <td>{{i.get_ticket_type_display}} </td> -->
                                                <td>{{ i.coupons.name }}</td>
                                                <td>{{ i.amount }}</td>
                                                <td>{{ i.extra }}</td>
                                                <td>{{ i.end_date|date:'Y-m-d' }}</td>
                                                <td class="{% if i.status == 0%}o{% elif i.status == 1 %}g{% else %}r{% endif %}">{{i.get_status_display}} </td>
                                            </tr>
                                        {% empty %}
                                        <tr class="text-center">
                                            <td colspan="10">没有找到匹配的记录</td>
                                        </tr>
                                        {% endfor %}
                                        

                                    </tbody>

                                    <script id="data-tmpl" type="text/x-jquery-tmpl">
                                         
                                    </script>

                                </table>
                            </form>
                        </div>
                        {% include 'common/page.html' %}
                    </div>
                </div>
            </div>
        </div>



<style type="text/css">
    .unit{
      display: inline-block;

    }
    .le{
        margin-left: 15%!important
    }
    .r{
        color: red
    }
    .o{
        color: orange
    }
    .g{
        color: green
    }
</style>
<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}

{% block js %}

<script>
    $('.chosen-select').chosen({'width': '200px'});
    function su(t){
        console.log(t);
        $('#op-form input[name=action]').val(t);
        $('#op-form').submit()
    }

</script>

{% endblock %}

parking/chargerule/templates/test.html
<div class="tim_body">
    <div id='tit'>
        <p1 >时段选择（支持多段）</p1>
    </div>
    <div class="it">
        {% for i in num %}
        <div style="display: inline-block;">
            <div class="item" id='item_{%  widthratio i.k 1 2 %}' onclick="setPointer(this,{%  widthratio i.k 1 2 %})"></div>
            <div class="sim" style="{% if i.v == '2'%}color:white{% endif %} ">{{ i.v}}</div>
        </div>
        {% endfor %}
    </div>
    <div class="it">
        {% for j in num1%}
        <div style="display: inline-block;">
            <div class="item" id='item_{%  widthratio j.k 1 2 %}' onclick="setPointer(this,{%  widthratio j.k 1 2 %})"></div>
            <div class="sim" style="{% if j.v == '2'%}color:white{% endif %} ">{{j.v}}</div>
        </div>
        {% endfor %}
    </div>
    <div style="margin-top: 10px;" class="it">
        已选时间段：<input type="text" id='tim_con'>
    </div>
    <div style="text-align: center;margin-top: 20px;">
        <input type="button" value="确定" class="btn btn-primary" onclick="show()">
        <input type="button" value="清除"  class="btn btn-primary" onclick="clea()">
        <input type="button" value="取消"  class="btn btn-primary" onclick="canc()">
    </div>

</div>
<style type="text/css">
        .it{
            margin-left: 40px
        }
        #tit{
            text-align: center;
            margin-top: 20px;
            margin-bottom: 35px;
        }
        .item{
           
            background-color: white;
            width: 30px;
            margin-left: -4px;
            border: 0.5px solid rgba(210, 210, 210, 0.5);
            font-size: 8pt;
            height: 30px; 
        }
        .sim{
            margin: 5px 0 0 -7px;
            font-size: 8px;
        }
        .tim_body{
            background: white;
            position: fixed;
            margin: 30px 18px 0px 50px;
            width:800px;
            height: 300px;
            border: 1px solid rgba(210, 210, 210, 0.5);
            right: 200px
        }
</style>

<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
<script>
var key = true;
var list = []
var time_list = []
var nam ;
function setPointer(obj,tip){
    var s = list.length%2
    var tail = list.length-1
    tip = parseInt(tip)
    base_c = 'white'
    var_c = 'red'


    function generate(start,end,t=0){
        for(var i=start;i<=end;i++){
            if(t == 0){
                $('#item_'+i).css('background-color',var_c)
            }else{
                $('#item_'+i).css('background-color',base_c)
            }
            
        }
        return true
    }


    function check(tip){
        if(time_list.length > 0){
            for(var i=0;i<time_list.length;i++){
                var m = time_list[i]
                if(m[0] <=tip && m[1] >= tip){
                    generate(m[0],m[1],1);
                    time_list.splice(i,1);
                    set_curr()

                }

            }
        }

    }
    function check_contain(start,end){
        if(time_list.length > 0){
            for(var i=0;i<time_list.length;i++){
                var m = time_list[i]
                if(m[0] >=start && m[1] >= start && m[0] <=end && m[1]<=end){
                    generate(m[0],m[1],1);
                    time_list.splice(i,1);
                    set_curr()

                }

            }
        }


    }

    // function check_near(tip){
    //     if(time_list.length > 0){
    //         for(var i=0;i<time_list.length;i++){
    //             var m = time_list[i]
    //             if(m[0] +1 == tip){
    //                 m[0] == tip;
    //                 check_near(tip)
    //             }else if(m[1] == tip +1){
    //                 m[1] == tip;
    //                 check_near(tip)
    //             }

    //         }
    //     }

    // }
    check(tip)

    if(s == 0){
        $('#item_'+tip).css('background-color',var_c);
        list.push(tip)
    }else{
        if(list[tail] > tip){
            check_contain(tip,list[tail]);
            generate(tip,list[tail]);
            list.push(tip)
        }
        else if(list[tail] == tip){
            $('#item_'+tip).css('background-color',base_c);
            list.pop(tail);

        }
        else{
            check_contain(list[tail],tip)
            generate(list[tail],tip);
            list.push(tip)
        }

    }
    
    if(list.length == 2){
        if(list[0] >list[1]){
            time_list.push([list[1],list[0]]);
          
        }else{
            time_list.push([list[0],list[1]]);
            
            
        }
        set_curr()
        list = []
    }
}
function save(){
    $(tmp).val(time_list)
}

function show(){
    var tmp = []
    if(time_list.length >0){
        for(var i=0;i<time_list.length;i++){
            tmp.push(time_op(time_list[i][0]/2,(time_list[i][1]+1)/2))
        }
        $(nam).val(tmp);
        
    }
    $('#time_div').hide() 
    



}
function clea(){
    for(var i=0;i<48;i++){
        $('#item_'+i).css('background-color','white')
    }
    list = []
    time_list = []
    $('#tim_con').val('')
}

function canc(){
    clea();
    $('#time_div').hide()

    
}
function set_tim(obj){
    time_list = [];
    list =[];
    $('#tim_con').val();
    for(var i=0;i<48;i++){
        $('#item_'+i).css('background-color','white')
    }
    $('#tim_con').val('');
    $('#time_div').show();
    nam = obj;  
}
function set_curr(){
    var tmp = []
    if(time_list.length >0){
        for(var i=0;i<time_list.length;i++){
            tmp.push(time_op(time_list[i][0]/2,(time_list[i][1]+1)/2))
        }
        $('#tim_con').val(tmp);
        
    }

}

function time_op(start,end){
    start = ''+start
    end = ''+ end

    return re_time(start)+'--'+re_time(end)
}
function re_time(str){
    console.log(str)
    if(str.replace(/\.5/,':30') == str){
        return str+':00'
    }else{
        return str.replace(/\.5/,':30')
    }
}
   
</script>