parking/parking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from administrator import views as a
from car import views as car
from device import views as device
from parkinglot import views as park
from company import views as com
from wechat import views as wechat
from chargerule import views as charge
from realtime import views as realtime
from account import views as ac
from business import views as b
from manager import views as m


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('meta.urls')),


    # administrator
    path('',a.base),
    path('administrator/login/',a.login),
    path('administrator/logout/',a.logout),
    path('base/', a.base),   
    path('index/', a.index),
    path('administrator/log/', a.log),
    path('administrator/role/', a.role),
    path('administrator/role/<int:id>/', a.get_role),
    path('administrator/user/',a.user),
    path('administrator/modify/',a.modify),
    

    # user



    # car 
    path('car/inner_car/', car.inner_car),  
    

    # parkinglot

    path('parkinglot/parking_lot/',park.parking_lot),
    path('parkinglot/gate/',park.gate),
    path('parkinglot/worker/', park.worker),
    path('parkinglot/zone/',park.zone),
    path('parkinglot/place/',park.place),
    path('parkinglot/calendar/',park.calendar),



    # company

    path('company/company/',com.company),



    # device

    path('device/brake/',device.brake),
    path('device/camera/',device.camera),
    path('device/groundsensor/',device.groundsensor),



    # chargerule

    path('chargerule/baserule/',charge.base_rule),
    path('chargerule/card/',charge.card),
    path('chargerule/coupon/',charge.coupon),
    path('chargerule/cardtype/',charge.card_type),
    path('chargerule/coupontype/',charge.coupon_type),
    path('chargerule/chargedemo/',charge.chargedemo),
    path('chargerule/check_coupon/',charge.check_coupon),


    # realtime

    path('realtime/parkin/',realtime.parkin),
    path('realtime/in_out/',realtime.in_out),
    path('realtime/bill/',realtime.bill),


    # wechat
    path('wechat/parkin/<int:parkinglot_id>/<int:gate_id>/',wechat.parkin),
    path('wechat/parkout/<int:parkinglot_id>/<int:gate_id>/',wechat.parkout),
    path('wechat/parkout/<int:parkinglot_id>/',wechat.parkout),
    path('wechat/personal/mybill/<int:id>/',wechat.mybill),
    path('wechat/personal/mybill/',wechat.mybill),
    path('wechat/personal/mycard/',wechat.mycard),
    path('wechat/personal/mycoupon/',wechat.mycoupon),
    path('wechat/personal/myplate/bound/',wechat.bound),
    path('wechat/personal/myplate/',wechat.myplate),
    path('wechat/personal/',wechat.personal),
    path('wechat/problem/',wechat.problem),
    path('wechat/scan/coupon/<int:id>/<str:code>/',wechat.scan_coupon),


    #account
    path('account/spec_pass/',ac.spec_pass),
    path('account/correct/',ac.correct),
    path('account/record/',ac.record),
    path('account/personal/',ac.personal,name='personal'),
    path('account/begin_work/',ac.begin_work),


    #business
    path('business/com_login/',b.com_login),
    path('business/apply/<int:tc_id>/',b.apply),
    path('business/grant/',b.grant),
    path('business/ticket/<int:tc_id>/',b.ticket),

    #manager
    path('manager/manage_login/',m.manage_login),
    path('manager/staff_list/<str:parkinglot>/',m.staff_list),
    path('manager/manage_home/',m.manage_home),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parking/administrator/models.py
from django.db import models

# Create your models here.


'''系统设置模块'''


class AdminUser(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '系统用户'

    status = models.IntegerField(default=0)
    user_name = models.CharField(max_length=30, unique=True, verbose_name='用户账号')
    user_pass = models.CharField(max_length=30,  verbose_name='密码')
    role_name = models.ForeignKey('Role',null=True,on_delete=models.CASCADE)
    phone = models.CharField(verbose_name='电话号码',max_length=30)
    sex = models.IntegerField(null=True,choices=[(0,'男'),(1,'女')],verbose_name='性别' ,default=0)
    real_name = models.CharField(max_length=30,verbose_name='姓名')
    remark = models.CharField(max_length=100,verbose_name='备注')

    def display_sex(self):
        if self.sex == 0:
            return '男'
        else:
            return '女'


class Role(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '用户角色'

    role_name = models.CharField(max_length=100, unique=True, verbose_name='用户名')
    detail = models.CharField(max_length=200, null=True, verbose_name='说明')

    def get_auth_ids(self):
        auths = Authority.objects.filter(role=self)
        menu = set()
        child_menu = set()
        operation = set()

        for i in auths:
            menu.add(i.menu.id)
            child_menu.add(i.child_menu.id)
            for j in i.operation.all():
                operation.add(j.id)

        return {'menu': menu, 'child_menu': child_menu, 'operation': operation}

    def get_menu_and_childmenu(self):
        menus = []

        if self.role_name == 'Admin':
            m = Menu.objects.filter(parent=None)
            for i in m:
                child_menu = Menu.objects.filter(parent=i)
                menus.append({
                    'id':i.id,
                    'menu': i.menu_name,
                    'child_menu': [{'child_menu': _.menu_name, 'url': _.url} for _ in child_menu]
                    })
        else:
            auths = Authority.objects.filter(role=self)
            
            for i in auths:
                flag = False
                for j,v in enumerate(menus):
                    if v['id'] == i.menu.id:
                        flag = True
                        menus[j]['child_menu'].append({'child_menu': i.child_menu.menu_name, 'url': i.child_menu.url})

                if not flag:
                    menus.append({
                        'id':i.menu.id,
                        'menu': i.menu.menu_name,
                        'child_menu': [{'child_menu': i.child_menu.menu_name, 'url': i.child_menu.url}]
                        })
        return menus

    def get_operations(self, url):
        menu = Menu.objects.filter(url=url).first()

        if not menu:
            return []
        else:
            if self.role_name == 'Admin':
                return [i.action for i in menu.operation.all()]
            auth = Authority.objects.filter(role=self, child_menu=menu)

            if auth:
                return [i.action for i in auth.first().operation.all()]
            else:
                return []


class Menu(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '菜单'

    menu_name = models.CharField(max_length=100, default='', unique=True, verbose_name='菜单名称')
    parent = models.ForeignKey('Menu', null=True, on_delete=models.CASCADE)
    url = models.CharField(max_length=200, unique=True, null=True, verbose_name='相对路径url')

    operation = models.ManyToManyField('Operation', verbose_name='操作')

    def __str__(self):
        return self.menu_name


class Operation(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '操作(功能)'

    operation_name = models.CharField(max_length=100, default='', verbose_name='操作名称')
    action = models.CharField(max_length=100, default='', verbose_name='方法名')

    def __str__(self):
        return self.operation_name
        

class Authority(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '权限'

    role = models.ForeignKey(Role, on_delete=models.CASCADE, verbose_name='角色')
    menu = models.ForeignKey(Menu, on_delete=models.SET_NULL,null=True, related_name='parent_menu', verbose_name='以及菜单')
    child_menu = models.ForeignKey(Menu, on_delete=models.SET_NULL,null=True, related_name='child_menu', verbose_name='二级菜单')
    operation = models.ManyToManyField(Operation)


class Settings(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '系统参数'

    pass


class Options(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '系统类别明细'

    pass


class Log(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = '操作日志'
        indexes = [
            models.Index(
                fields=['create_day'],
                name='create_day_idx',
            ),
        ]
    ip = models.CharField(max_length=100, null=True, blank=True, verbose_name='ip')
    operation = models.CharField(max_length=100, null=True, blank=True, verbose_name='操作')
    content = models.CharField(max_length=100, null=True, blank=True, verbose_name='操作内容')
    model = models.CharField(max_length=100, null=True, blank=True, verbose_name='操作模块')
    user = models.ForeignKey(AdminUser, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='操作用户')

    create_time = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    create_day = models.IntegerField(null=True, blank=True)

 

   

parking/administrator/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


from .models import *
from .decorators import page, _save_attr_
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .decorators import user_required
from django.shortcuts import redirect


'''系统设置模块'''

@csrf_exempt
def login(request):
    
    if request.method == 'POST':
        
        action = request.POST.get('action','')
        if action == 'login':
            user_name = request.POST.get('user_name')
            password = request.POST.get('user_pass')
             
            user = AdminUser.objects.filter(user_name=user_name,user_pass=password).first()
            if user :
                 
                request.session['uid'] = user.id
                request.session['user_name'] = user.user_name

                request.session['role'] = user.role_name.role_name
                request.session['menus'] = menus = user.role_name.get_menu_and_childmenu()

                return redirect(base)

    return render(request, 'login.html')


def logout(request):
    
    if 'uid' in request.session:
        del(request.session['uid'])
    if 'user_name' in request.session:
        del(request.session['user_name'])

    return render(request, 'login.html')



@user_required
def base(request, user):
    print('sss')
    return render(request, 'common/base.html')

@user_required
def modify(request, user):
    ctx={}
    
    if request.method == 'POST':

        action = request.POST.get('action','')
        if action == 'update':
            id = request.POST.get('id', '')

            r = AdminUser.objects.filter(id=id).first()
            _save_attr_(r, request)
            role = request.POST.get('role_name','')
            if role:
                role = Role.objects.filter(id=int(role)).first()
                r.role_name = role
                r.save()
            

    ctx['me'] =  user
    ctx['roles'] = roles = Role.objects.all()

    return render(request,'perModify.html',ctx)


def skin(request):
    return render(request, 'skin.html')
    

def index(request):
    
    return render(request, 'index.html')


def log(request):
    
    return render(request, 'log.html')


@page
def user(request):
    ctx = {}

    def op(r,request):
        _save_attr_(r, request)
        role = request.POST.get('user_role','')
        if role:
            r.role_name = Role.objects.filter(id=role).first()
            r.save()

    users = AdminUser.objects.exclude(status=-1).all()
    roles = Role.objects.all()

    if request.method == 'POST':
        action = request.POST.get('action','')
        if action == 'add':
            r = AdminUser()
            op(r,request)

        elif action == 'update':
            id = request.POST.get('id', '')
            r = AdminUser.objects.filter(id=id).first()
            op(r,request)

        elif action == 'delete':
            ids = request.POST.getlist('ids', '')
            u = AdminUser.objects.filter(id__in=ids).all()
            for item in u:
                item.status = -1
                item.save()
        elif action == 'validate':
            user_name = request.POST.get('user_name', '')
            id = request.POST.get('id','')
            if id:
                r = AdminUser.objects.filter(user_name=user_name.strip()).exclude(id=int(id))
            else:   
                r = AdminUser.objects.filter(user_name=user_name.strip())
            if r.exists():
                    return JsonResponse({'valid': False})

            return JsonResponse({'valid': True})

        elif action =='select':
            role = request.POST.get('role_name','')
            user = request.POST.get('user_name','')
            if role:
                users = users.filter(role_name__id=role).all()
            if user:
                users = users.filter(user_name__icontains=user)
            ctx['u'] = user
            ctx['r'] = int(role) if role else ''


    ctx['users'] = ctx['objects'] = users
    ctx['roles'] = roles

    return (ctx,'user.html')


@csrf_exempt
@user_required
@page
def role(request, user):
    ctx = {}

    roles = Role.objects.all()

    if request.method == 'POST':
        action = request.POST.get('action', '')
        if action == 'add':
            r = Role()
            _save_attr_(r, request)

            save_auth(r, request)

        elif action == 'update':
            id = request.POST.get('id', '')

            r = Role.objects.filter(id=id).first()
            _save_attr_(r, request)
            save_auth(r, request)

        elif action == 'search':
            ctx['role_name'] = role_name = request.POST.get('role_name', '')
            roles = Role.objects.filter(role_name__contains=role_name.strip())

        elif action == 'delete':
            ids = request.POST.getlist('ids', '')
            Role.objects.filter(id__in=ids).delete()

        elif action == 'validate':
            role_name = request.POST.get('role_name', '')
            id = request.POST.get('id', '')

            r = Role.objects.filter(role_name=role_name.strip())
            if r.exists():
                if id:
                    if r.first().id != int(id):
                        return JsonResponse({'valid': False})
                else:
                    return JsonResponse({'valid': False})

            return JsonResponse({'valid': True})

    ctx['objects'] = roles

    ctx['menus'] = Menu.objects.filter(parent=None).order_by('id')

    return (ctx, 'role.html')


@csrf_exempt
def get_role(request, id):
    ctx = {}

    ctx['role'] = r = Role.objects.filter(id=id).first()
    ctx['auth'] = r.get_auth_ids()
    ctx['menus'] = Menu.objects.filter(parent=None).order_by('id')

    return render(request, 'edit_role.html', ctx)


def save_auth(r, request):
    menus = request.POST.getlist('menu', [])
    child_menus = request.POST.getlist('child_menu', [])
    operations = request.POST.getlist('operation', [])

    Authority.objects.filter(role=r).delete()

    for i in child_menus:
        child_menu = Menu.objects.filter(id=i).first()
        auth = Authority.objects.create(role=r, menu=child_menu.parent, child_menu=child_menu)
        ops = child_menu.operation.filter(id__in=operations)

        for j in ops:
            auth.operation.add(j)

    return

parking/administrator/templates/edit_role.html
    
    <div class="layui-layer-shade" id="layui-layer-shade6" times="6" style="z-index: 19891019; background-color: rgb(0, 0, 0); opacity: 0.3;"></div>
        <div class="layui-layer layui-layer-iframe" id="layui-layer6" type="iframe" times="6" showtime="0" contype="string" style="z-index: 19891020; width: 820px; height: 580px; top:20.5px; left: 215px;">
            <div class="layui-layer-title" style="cursor: move;"><i class="fa fa-car"></i> 修改角色</div>
            <div id="" class="layui-layer-content"><div class="ibox-content">
                <div class="form-horizontal" id="verifyCheck">
                    <form id='update_form' action='' method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">角色名称</label>
                            <div class="col-sm-4">
                                <input type="text" name="role_name" value='{{role.role_name}}' class="form-control required">
                            </div>
                            <label class="col-sm-1 control-label">说明</label>
                            <div class="col-sm-4">
                                <input type="text" name="detail"  value='{{role.detail|default:""}}' class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权限明细</label>
                            <div class="col-sm-4">
    <!-- 切勿随意修改这段代码的结构 !!!! -->
{% for menu in menus %}
<div>      
    <input type='checkbox' value='{{ menu.id }}' class='menu'  name='menu'
        {% for xx in auth.menu %}
            {% if menu.id == xx %}checked{% endif %}
        {% endfor %}
     />  {{ menu.menu_name }}
        {% for child in menu.menu_set.all %}
        <div style="padding-left: 30px">
            <input type='checkbox' value='{{ child.id }}' class='child_menu' name='child_menu'
                {% for xx in auth.child_menu %}
                    {% if child.id == xx %}checked{% endif %}
                {% endfor %}
            />  {{ child.menu_name }}
                <div style="padding-left: 30px">
                {% for op in child.operation.all %}
                    <input type='checkbox' value='{{ op.id }}' class='operation' name='operation'
                        {% for xx in auth.operation %}
                            {% if op.id == xx %}checked{% endif %}
                        {% endfor %}
                    />   {{op.operation_name}}
                {% empty %}
                {% endfor %}
                </div>
        </div>
        {% empty %}
        {% endfor %}
</div>
{% empty %}
{% endfor %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <input type="hidden" name="id" class="form-control" value='{{role.id}}'>
                                <input type="hidden" name="action" class="form-control" value='update'>
                                <button type="submit" class="btn btn-primary" style="display: inline-block;"><i class="fa fa-check"></i> 保存</button>&nbsp;
                                <button class="btn btn-warning cancel" type="button" style="display: inline-block;"><i class="fa fa-times"></i> 取消</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div></div>
            <span class="layui-layer-setwin">
                <!-- <a class="layui-layer-min" href="javascript:;"><cite></cite></a>
                <a class="layui-layer-ico layui-layer-max" href="javascript:;"></a> -->
                <a class="layui-layer-ico layui-layer-close layui-layer-close1" href="javascript:;"></a>
            </span>
            <span class="layui-layer-resize"></span></div>
<script type="text/javascript">
    $('#update_form').bootstrapValidator({

    　　　　　　　　  message: 'This value is not valid',
    　 feedbackIcons: {
        　　　　　　　　valid: 'glyphicon glyphicon-ok',
        　　　　　　　　invalid: 'glyphicon glyphicon-remove',
        　　　　　　　　validating: 'glyphicon glyphicon-refresh'
    　　　　　　　　   },

        fields: {
            role_name: {
                message: '角色名不能为空',
                validators: {
                    notEmpty: {
                        message: '角色名不能为空'
                    },
                    stringLength: {
                         min: 3,
                         max: 20,
                         message: '角色名长度必须在3到20之间'
                     },
                    remote:{
                        url: '',
                        data:function(validator) {
                            return {
                                id: $('input[name=id]').val(),
                                role_name: $('input[name=role_name]').val(),
                                action: 'validate',
                            }
                        },
                        type:'post',
                        message: '角色名已存在'
                    }
                },

                
            }
        }
    });


    $('.menu').click(function(){
        var checked = $(this).prop('checked')
        $(this).parent().find('input[type=checkbox]').prop('checked', checked)
    })
    $('.child_menu').click(function(){
        var checked = $(this).prop('checked')
        $(this).parent().find('.operation').prop('checked', checked)
        
        if($(this).parent().parent().find('.child_menu:checked').length >0){
            $(this).parent().parent().find('.menu').prop('checked', true)
        }else{
            $(this).parent().parent().find('.menu').prop('checked', false)
        }
    })
    $('.operation').click(function(){
        var checked = $(this).prop('checked')

        if($(this).parent().find('.operation:checked').length >0){
            $(this).parent().parent().find('.child_menu').prop('checked', true)
        }else{
            $(this).parent().parent().find('.child_menu').prop('checked', false)
        }

        if($(this).parent().parent().find('.child_menu:checked').length >0){
            $(this).parent().parent().parent().find('.menu').prop('checked', true)
        }else{
            $(this).parent().parent().parent().find('.menu').prop('checked', false)
        }

    })

    $('.layui-layer-close').click(function(){
            $('.model').hide()
        })
        $('.cancel').click(function(){
            $('.model').hide()
        })

</script>

parking/administrator/templates/log.html
{% extends 'iframe.html' %}
{% block content %}
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <ol class="col-lg-5 breadcrumb">
                            <li>系统配置</li>
                            <li>日志管理</li>
                        </ol>
                        <div class="ibox-tools">
                            <a onclick="window.location.href=window.location.href; "><i class="fa fa-refresh animated rotateIn"></i>&nbsp; 重新载入</a>
                        </div>
                    </div>
                    <div class="ibox-content" id="searchForm">
                        <div class="form-inline ">
                            <form id='query_form' action='' method="post">
                                {% csrf_token %}
                                <div class="form-inline">
                                    <div class="form-group">
                                        <input type="text" placeholder="" class="form-control" id="role_name" name="role_name" value='{{role_name}}'>
                                    </div>
                                    <div class="form-group">
                                        <input type='hidden' name='action' value='search' />
                                        <input type='hidden' name='page' value='1' id='page' />
                                        <input type='hidden' name='pagesize' value='10' id='pagesize' />
                                        <button id='search-btn' class="btn btn-primary search-btn " type="button" style="display: inline-block;">
                                            <i class="fa fa-search"></i> 查 询
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-sm-6 m-b-xs">
                                <button type="button" id="Add" class=" btn btn-primary model-btn" data-target='add_role_model' style="display: inline-block;"><i class="fa fa-plus"></i>&nbsp;新增</button>
                                <button type="button" id="update-btn" class="btn btn-primary " style="display: inline-block;"><i class="fa fa-edit"></i>&nbsp;修改</button>
                                <button type="button" id="delete-btn" class="btn btn-primary " style="display: inline-block;"><i class="fa fa-trash"></i>&nbsp;删除</button>
                            </div>
                            <div class="col-sm-3 m-b-xs"></div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped  table-hover">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody id="data-view">
                                    <form id='delete-form' action="" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" name="action" value='delete'>
                                    {% for i in objects %}
                                        <tr>
                                         <td><input name='ids' type='checkbox' value='{{i.id}}' /></td>
                                            <td>{{ i.role_name }}</td>
                                            <td>{{ i.detail|default:''}}</td>
                                        </tr>
                                    {% empty %}
                                    <tr class="text-center">
                                        <td colspan="11">没有找到匹配的记录</td>
                                    </tr>
                                    {% endfor %}
                                    </form>

                                </tbody>

                                <script id="data-tmpl" type="text/x-jquery-tmpl">
                                     
                                </script>

                            </table>
                        </div>
                        {% include 'common/page.html' %}
                    </div>
                </div>
            </div>
        </div>

<!-- update model -->
        <div id='update_model' class='model'>
        </div>
<!-- add model -->
       <div id='add_role_model' class='model'>
        <div class="layui-layer-shade" id="layui-layer-shade6" times="6" style="z-index: 19891019; background-color: rgb(0, 0, 0); opacity: 0.3;"></div>

        <div class="layui-layer layui-layer-iframe" id="layui-layer6" type="iframe" times="6" showtime="0" contype="string" style="z-index: 19891020; width: 820px; height: 580px; top:20.5px; left: 215px;">
            <div class="layui-layer-title" style="cursor: move;"><i class="fa fa-car"></i> 新增角色</div>
            <div id="" class="layui-layer-content"><div class="ibox-content">
                <div class="form-horizontal" id="verifyCheck">
                    <form id='add_form' action='' method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">角色名称</label>
                            <div class="col-sm-4">
                                <input type="text" name="role_name" class="form-control required">
                            </div>
                            <label class="col-sm-1 control-label">说明</label>
                            <div class="col-sm-4">
                                <input type="text" name="detail" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">权限明细</label>
                            <div class="col-sm-4">
    
{% for menu in menus %}
<div>
    <input type='checkbox' value='{{ menu.id }}' class='menu' name='menu' />  {{ menu.menu_name }}
        {% for child in menu.menu_set.all %}
        <div style="padding-left: 30px">
            <input type='checkbox' value='{{ child.id }}' class='child_menu' name='child_menu'
            parent='menu_{{ menu.id }}' />  {{ child.menu_name }}
                <div style="padding-left: 30px">
                {% for op in child.operation.all %}
                    <input type='checkbox' value='{{ op.id }}' class='operation' name='operation' />   {{op.operation_name}}
                {% empty %}
                {% endfor %}
                </div>
        </div>
        {% empty %}
        {% endfor %}
</div>
{% empty %}
{% endfor %}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>
                        
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <input type="hidden" name="action" class="form-control" value='add'>

                                <button type="submit" class="btn btn-primary" style="display: inline-block;"><i class="fa fa-check"></i> 保存</button>&nbsp;
                                <button class="btn btn-warning cancel" type="button" style="display: inline-block;"><i class="fa fa-times"></i> 取消</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div></div>
            <span class="layui-layer-setwin">
                <!-- <a class="layui-layer-min" href="javascript:;"><cite></cite></a>
                <a class="layui-layer-ico layui-layer-max" href="javascript:;"></a> -->
                <a class="layui-layer-ico layui-layer-close layui-layer-close1" href="javascript:;"></a>
            </span>
            <span class="layui-layer-resize"></span></div>
       </div>
    </div>
{% endblock %}